version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    ports:
      - "3000:80"
